# Generated by Django 5.2.7 on 2025-10-09 15:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading text', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Body text for the hero section', 'required': True}), 2: ('wagtail.blocks.EmailBlock', (), {'help_text': 'Email address for contact', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phone number for contact', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body_text', 1), ('cta_email', 2), ('cta_phone', 3)]], {})}),
        ),
    ]
