# Generated by Django 5.2.7 on 2025-10-09 16:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('section', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading text', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Body text for the hero section', 'required': True}), 2: ('wagtail.blocks.EmailBlock', (), {'help_text': 'Email address for contact', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phone number for contact', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body_text', 1), ('cta_email', 2), ('cta_phone', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title (h2)', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark')], 'help_text': 'Section background color'}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Paragraph of text'}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('features', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('heading', 8), ('description', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('topics', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('paragraph', 7), ('features', 12), ('topics', 16)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 5), ('background', 6), ('content', 17)]], {})}),
        ),
    ]
