# Generated by Django 5.2.7 on 2025-10-09 18:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('section', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading text', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Body text for the hero section', 'required': True}), 2: ('wagtail.blocks.EmailBlock', (), {'help_text': 'Email address for contact', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Phone number for contact', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body_text', 1), ('cta_email', 2), ('cta_phone', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title (h2)', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark')], 'help_text': 'Section background color'}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4'], 'help_text': 'Heading (h4)'}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Paragraph of text'}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('3', '3 columns (h4 headings)'), ('4', '4 columns (h6 headings)')], 'help_text': 'Number of columns in grid layout'}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 12: ('wagtail.blocks.StructBlock', [[('heading', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('columns', 9), ('features', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Definition term (dt)', 'max_length': 100, 'required': True}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Definition description (dd)', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('term', 15), ('definition', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('items', 18)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 7), ('paragraph', 8), ('features', 14), ('definition_list', 19)]], {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('title', 5), ('background', 6), ('content', 20)]], {})}),
        ),
    ]
